### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Vigneshsab** [polo8214/Brain-tumor-segmentation#1]
Hey, could you please send the files which are mentioned in the below code

#%%
# catch all T1c.mha
create_data('/home/andy/Brain_tumor/BRATS2015/BRATS2015_Training/HGG/', '**/*Flair*.mha', label=False, resize=(155,img_size,img_size))
create_data('/home/andy/Brain_tumor/BRATS2015/BRATS2015_Training/HGG/', '**/*OT*.mha', label=True, resize=(155,img_size,img_size))

#%%
# catch BRATS2017 Data
create_data('/home/andy/Brain_tumor/BRATS2017/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations/', '**/*_flair.nii.gz', label=False, resize=(155,img_size,img_size))
create_data('/home/andy/Brain_tumor/BRATS2017/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations/', '**/*_GlistrBoost_ManuallyCorrected.nii.gz', label=True, resize=(155,img_size,img_size))

#%%
# load numpy array data
x = np.load('/home/andy/x_{}.npy'.format(img_size))
y = np.load('/home/andy/y_{}.npy'.format(img_size))

**Comment by AndyWangON** [comment]
You can Download it at here
https://www.smir.ch/BRATS/Start2015
